CREATE TABLE SCDETSECUENCIAS(
	NOMBRESECUENCIA VARCHAR(32),
    VALORSECUENCIA INTEGER,
	PRIMARY KEY(NOMBRESECUENCIA)
);

INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECUSUARIO', 2);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECMODULOS', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECPERFIL', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECSUCURSAL', 2);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECPERSONA', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECEMPRESA', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECCONTACTO', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECCLIENTE', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECORDEN', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECORDENDETALLE', 1);
INSERT INTO SCDETSECUENCIAS(NOMBRESECUENCIA,VALORSECUENCIA) VALUES('SCDESECESTADOORDEN', 1);

CREATE TABLE SCDETSUCURSAL(
	CODIGOSUCURSAL INTEGER NOT NULL,
	NOMBREEMPRESA VARCHAR(10) NOT NULL,
	NOMBRESUCURSAL VARCHAR(64) NOT NULL,
	DIRECCION VARCHAR(256),
	CIUDAD VARCHAR(64),
	SERIE VARCHAR(32),
	ESTADO VARCHAR(1) NOT NULL, 
	PRIMARY KEY(CODIGOSUCURSAL)
);
INSERT INTO SCDETSUCURSAL (CODIGOSUCURSAL, NOMBRESUCURSAL, DIRECCION, CIUDAD, SERIE, ESTADO) 
VALUES(1, 'UHEXPRESS','SUCURSAL IBARRA', 'AV. 13 DE ABRIL Y CAÑAR', 'IBARRA', '001','1');

CREATE TABLE SCDETPERFIL(
	CODIGOPERFIL DECIMAL(12 , 0) NOT NULL,
	NOMBREPERFIL VARCHAR(64) NOT NULL,
	DESCRIPCION VARCHAR(256),
	ESTADO VARCHAR(1) NOT NULL,
	PRIMARY KEY(CODIGOPERFIL)
);
INSERT INTO SCDETPERFIL(CODIGOPERFIL, NOMBREPERFIL, DESCRIPCION,  ESTADO) VALUES(1, 'PERFIL ADMINISTRADOR', 'PERFIL PARA USUARIO ADMINISTRADORES DE LA APP', '1');

CREATE TABLE SCDETMODULOS(
	CODIGOMODULO DECIMAL(12, 0) NOT NULL,
	CODIGOREFERENCIA VARCHAR(16) NOT NULL,
	ORDEN INTEGER NOT NULL,
	NOMBREMODULO VARCHAR(64) NOT NULL,
	DESCRIPCION VARCHAR(64),
	ESTILO VARCHAR(32) NOT NULL,
	VALORTIPO VARCHAR(3), 
	URL VARCHAR(128) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,	
	PRIMARY KEY(CODIGOMODULO) 
);

INSERT INTO SCDETMODULOS(CODIGOMODULO, CODIGOREFERENCIA, ORDEN, NOMBREMODULO, DESCRIPCION, ESTILO, VALORTIPO, URL, ESTADO) VALUES (2, 'MOD-2', 2, 'CLIENTES', 'MODULO DE CLIENTES', 'styleClient', 'GES','/modules/clientes/adminBusquedaClientes.xhtml?faces-redirect=true','1');
INSERT INTO SCDETMODULOS(CODIGOMODULO, CODIGOREFERENCIA, ORDEN, NOMBREMODULO, DESCRIPCION, ESTILO, VALORTIPO, URL, ESTADO) VALUES (9, 'MOD-9', 9, 'USUARIOS', 'MODULO DE USUARIOS', 'styleUsuario', 'ADM','/modules/usuarios/adminBusquedaUsuarios.xhtml?faces-redirect=true','1');
INSERT INTO SCDETMODULOS(CODIGOMODULO, CODIGOREFERENCIA, ORDEN, NOMBREMODULO, DESCRIPCION, ESTILO, VALORTIPO, URL, ESTADO) VALUES (1, 'MOD-1', 3, 'ORDENES SERVICIO', 'MODULO DE ORDENES DE SERVICIO', 'stylePedidos', 'GES','/modules/ordenes/adminBusquedaOrdenes.xhtml?faces-redirect=true','1');
INSERT INTO SCDETMODULOS(CODIGOMODULO, CODIGOREFERENCIA, ORDEN, NOMBREMODULO, DESCRIPCION, ESTILO, VALORTIPO, URL, ESTADO) VALUES (10, 'MOD-10', 10, 'MODULOS', 'MODULO DE MODULOS', 'styleModulo', 'ADM','/modules/modulos/adminBusquedaModulos.xhtml?faces-redirect=true','1');
INSERT INTO SCDETMODULOS(CODIGOMODULO, CODIGOREFERENCIA, ORDEN, NOMBREMODULO, DESCRIPCION, ESTILO, VALORTIPO, URL, ESTADO) VALUES (11, 'MOD-11', 11, 'PERFILES', 'MODULO DE PERFILES', 'stylePerfil', 'ADM','/modules/perfiles/adminBusquedaPerfil.xhtml?faces-redirect=true','1');


CREATE TABLE SCDETCATALOGOVALOR(
	CODIGOCATALOGOVALOR VARCHAR(3) NOT NULL,
	CODIGOCATALOGOTIPO INTEGER NOT NULL,
	NOMBRECATALOGOVALOR VARCHAR(64) NOT NULL,
	ESTADO VARCHAR(1),
	PRIMARY KEY(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO)
);

INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('PAQ', 1, 'PAQUETE', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('DOC', 1, 'DOCUENTOS', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('DEL', 1, 'DELICADO', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('BUL', 1, 'BULTOS', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('PEL', 1, 'PELIGROSA', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('LES', 2, 'SUCURSAL', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('LED', 2, 'DOMICILIO', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('EMP', 3, 'EMPRESA', '1');
INSERT INTO SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO, NOMBRECATALOGOVALOR, ESTADO) VALUES('PER', 3, 'PERSONA', '1');



CREATE TABLE SCDETMODULOPERFIL(
	CODIGOMODULO DECIMAL(12, 0) NOT NULL,
	CODIGOPERFIL DECIMAL(12 , 0) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	PRIMARY KEY(CODIGOMODULO, CODIGOPERFIL) 
);
ALTER TABLE SCDETMODULOPERFIL ADD CONSTRAINT CODMODFKSCDETMODULOPERFILPKMODULO FOREIGN KEY(CODIGOMODULO) REFERENCES SCDETMODULOS(CODIGOMODULO);
ALTER TABLE SCDETMODULOPERFIL ADD CONSTRAINT CODPERFKSCDETMODULOPERFILPKPERFIL FOREIGN KEY(CODIGOPERFIL) REFERENCES SCDETPERFIL(CODIGOPERFIL);

INSERT INTO SCDETMODULOPERFIL(CODIGOMODULO, CODIGOPERFIL, ESTADO) VALUES(2, 1, '1');
INSERT INTO SCDETMODULOPERFIL(CODIGOMODULO, CODIGOPERFIL, ESTADO) VALUES(9, 1, '1');
INSERT INTO SCDETMODULOPERFIL(CODIGOMODULO, CODIGOPERFIL, ESTADO) VALUES(10, 1, '1');
INSERT INTO SCDETMODULOPERFIL(CODIGOMODULO, CODIGOPERFIL, ESTADO) VALUES(11, 1, '1');

CREATE TABLE SCDETUSUARIO(
	USERID VARCHAR(32) NOT NULL,
	CODIGOPERFIL DECIMAL(12 , 0) NOT NULL,
	CODIGOSUCURSAL INTEGER NOT NULL,
	NOMBREUSUARIO VARCHAR(32) NOT NULL,
	NOMBRECOMPLETO VARCHAR(64),
	PASSWORDUSUARIO VARCHAR(64),
	ESTADO VARCHAR(1) NOT NULL,	
	PRIMARY KEY(USERID)
);
ALTER TABLE SCDETUSUARIO ADD CONSTRAINT CODPERFKSCDETUSUARIOPKPERFIL FOREIGN KEY(CODIGOPERFIL) REFERENCES SCDETPERFIL;
ALTER TABLE SCDETUSUARIO ADD CONSTRAINT CODCOMFKSCDETUSUARIOPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
INSERT INTO SCDETUSUARIO(USERID, CODIGOPERFIL, CODIGOSUCURSAL, NOMBREUSUARIO, NOMBRECOMPLETO, PASSWORDUSUARIO, ESTADO) VALUES('USR1', 1, 1,'egudino', 'Esteban Gudiño', 'es13ban', '1');

CREATE TABLE SCDETPERSONA(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOPERSONA DECIMAL(12 , 0) NOT NULL,
	NUMERODOCUMENTO VARCHAR(32),
	PRIMERNOMBRE VARCHAR(32) NOT NULL,
	SEGUNDONOMBRE VARCHAR(32),
	PRIMERAPELLIDO VARCHAR(32) NOT NULL,
	SEGUNDOAPELLIDO VARCHAR(32),
	FECHANACIMIENTO TIMESTAMP,
	NOMBRECOMPLETO VARCHAR(128),
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOPERSONA)
);
ALTER TABLE SCDETPERSONA ADD CONSTRAINT CODCOMFKSCVNTPERSONAPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETPERSONA ADD CONSTRAINT CODUSRFKSCVNTPERSONAPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETPERSONA ADD CONSTRAINT CODUSRFKSCVNTPERSONAPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);

CREATE TABLE SCDETEMPRESA(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOEMPRESA DECIMAL(12 , 0) NOT NULL,
	NUMERORUC VARCHAR(32),
	RAZONSOCIAL VARCHAR(128) NOT NULL,
	DESCRIPCIONEMPRESA VARCHAR(128),
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOEMPRESA)
);
ALTER TABLE SCDETEMPRESA ADD CONSTRAINT CODCOMFKSCVNTEMPRESAPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETEMPRESA ADD CONSTRAINT CODUSRFKSCVNTEMPRESAPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETEMPRESA ADD CONSTRAINT CODUSRFKSCVNTEMPRESAPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);

CREATE TABLE SCDETCONTACTO(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOCONTACTO DECIMAL(12 , 0) NOT NULL,
	CODIGOPERSONA DECIMAL(12 , 0),
	CODIGOEMPRESA DECIMAL(12 , 0),
	DIRECCIONPRINCIPAL VARCHAR(256) NOT NULL, 
	CALLEPRINCIPAL VARCHAR(128) NOT NULL,
	CALLESECUNDARIA VARCHAR(128),
	NUMEROCASA VARCHAR(32),
	REFERENCIA VARCHAR(256),
	CIUDAD VARCHAR(64) NOT NULL,
	TELEFONOPRINCIPAL VARCHAR(32),
	TELEFONOCELULAR VARCHAR(32),
	EMAIL VARCHAR(64),
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOCONTACTO)	
);
ALTER TABLE SCDETCONTACTO ADD CONSTRAINT CODCOMFKSCVNTCONTACTOSPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETCONTACTO ADD CONSTRAINT CODUSRFKSCVNTCONTACTOPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETCONTACTO ADD CONSTRAINT CODUSRFKSCVNTCONTACTOPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETCONTACTO ADD CONSTRAINT CODPERFKSCVNTCONTACTOSPKPERSONA FOREIGN KEY(CODIGOSUCURSAL, CODIGOPERSONA) REFERENCES SCDETPERSONA;
ALTER TABLE SCDETCONTACTO ADD CONSTRAINT CODEMPFKSCVNTCONTACTOSPKEMPRESA FOREIGN KEY(CODIGOSUCURSAL, CODIGOEMPRESA) REFERENCES SCDETEMPRESA;

CREATE TABLE SCDETCLIENTE(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOCLIENTE DECIMAL(12 , 0) NOT NULL,
	CODIGOPERSONA DECIMAL(12 , 0),
	CODIGOEMPRESA DECIMAL(12 , 0),
	CODIGOVENDEDOR DECIMAL(12 , 0), 
	USERID VARCHAR(32),
	CODIGOVALORTIPOCLIENTE VARCHAR(3) NOT NULL,
	CODIGOTIPOCLIENTE INTEGER NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOCLIENTE)	
);
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODCOMFKSCVNTCLIENTEPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODUSRFKSCVNTCLIENTEPKUSUARIO FOREIGN KEY(USERID) REFERENCES SCDETUSUARIO;
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODUSRFKSCVNTCLIENTEPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODUSRFKSCVNTCLIENTEPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODPERFKSCVNTCLIENTEPKPERSONA FOREIGN KEY(CODIGOSUCURSAL, CODIGOPERSONA) REFERENCES SCDETPERSONA;
ALTER TABLE SCDETCLIENTE ADD CONSTRAINT CODEMPFKSCVNTCLIENTEPKEMPRESA FOREIGN KEY(CODIGOSUCURSAL, CODIGOEMPRESA) REFERENCES SCDETEMPRESA;


CREATE TABLE SCDETORDEN(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOORDEN DECIMAL(12 , 0) NOT NULL,
	NUMEROORDEN VARCHAR(32) NOT NULL,
	FECHAORDEN TIMESTAMP NOT NULL,
	FECHASALIDA TIMESTAMP,
	TOTALIMPORTE DECIMAL(12,4),
	CODIGOSUCURSALORIGEN INTEGER,
	CODIGOSUCURSALDESTINO INTEGER,
	CODIGOCLIENTEREMITENTE DECIMAL(12 , 0),
	CODIGOCLIENTEDESTINATARIO DECIMAL(12 , 0),
	DIRECCIONDESTINO VARCHAR(256),
	CODIGOVALORLUGARENTREGA VARCHAR(3) NOT NULL,
	CODIGOTIPOLUGARENTREGA INTEGER NOT NULL,
	CODIGOVALORTIPOCARGA VARCHAR(3) NOT NULL,
	CODIGOTIPOCARGA INTEGER NOT NULL,
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOORDEN)	
);
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODSUCFKSCDETORDENPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODSUCFKSCDETORDENPKSUCURSALORI FOREIGN KEY(CODIGOSUCURSALORIGEN) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODSUCFKSCDETORDENPKSUCURSALDES FOREIGN KEY(CODIGOSUCURSALDESTINO) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODUSRFKSCDETORDENPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODUSRFKSCDETORDENPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODCLIFKSCDETORDENPKCLIENTEREM FOREIGN KEY(CODIGOSUCURSAL, CODIGOCLIENTEREMITENTE) REFERENCES SCDETCLIENTE;
ALTER TABLE SCDETORDEN ADD CONSTRAINT CODCLIFKSCDETORDENPKCLIENTEDES FOREIGN KEY(CODIGOSUCURSAL, CODIGOCLIENTEDESTINATARIO) REFERENCES SCDETCLIENTE;
ALTER TABLE SCDETORDEN ADD CONSTRAINT CATVALFKSCDETORDENPKCATLUGENT FOREIGN KEY(CODIGOVALORLUGARENTREGA, CODIGOTIPOLUGARENTREGA) REFERENCES SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO);
ALTER TABLE SCDETORDEN ADD CONSTRAINT CATVALFKSCDETORDENPKCATTIPCAR FOREIGN KEY(CODIGOVALORTIPOCARGA, CODIGOTIPOCARGA) REFERENCES SCDETCATALOGOVALOR(CODIGOCATALOGOVALOR,CODIGOCATALOGOTIPO);

CREATE TABLE SCDETORDENDETALLE(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOORDENDETALLE DECIMAL(12 , 0) NOT NULL,
	CODIGOORDEN DECIMAL(12 , 0) NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	DESCRIPCION VARCHAR(256) NOT NULL,
	OBSERVACION VARCHAR(256),
	PESO DECIMAL(12, 4),
	COSTOPESOKILO DECIMAL(12 , 4),
	IMPORTE DECIMAL(12 , 4),
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOORDENDETALLE)	
);
ALTER TABLE SCDETORDENDETALLE ADD CONSTRAINT CODCOMFKSCDETORDENDETALLEPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETORDENDETALLE ADD CONSTRAINT CODUSRFKSCDETORDENDETALLEPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETORDENDETALLE ADD CONSTRAINT CODUSRFKSCDETORDENDETALLEPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETORDENDETALLE ADD CONSTRAINT CODPEDFKSCDETORDENDETALLEPKPEDIDO FOREIGN KEY(CODIGOSUCURSAL, CODIGOORDEN) REFERENCES SCDETORDEN;

CREATE TABLE SCDETESTADOORDEN(
	CODIGOSUCURSAL INTEGER NOT NULL,
	CODIGOESTADOORDEN DECIMAL(12 , 0) NOT NULL,
	CODIGOORDEN DECIMAL(12 , 0) NOT NULL,
	CODIGOVALORESTADOORDEN VARCHAR(3) NOT NULL,
	CODIGOTIPOESTADOORDEN INTEGER NOT NULL,
	FECHAINICIO TIMESTAMP NOT NULL,
	FECHAFIN TIMESTAMP,
	ESTADO VARCHAR(1) NOT NULL,
	USUARIOREGISTRO VARCHAR(32) NOT NULL,
	FECHAREGISTRO TIMESTAMP NOT NULL,
	USUARIOMODIFICACION VARCHAR(32),
	FECHAMODIFICACION TIMESTAMP,
	PRIMARY KEY(CODIGOSUCURSAL, CODIGOESTADOORDEN, CODIGOORDEN)	
);
ALTER TABLE SCDETESTADOORDEN ADD CONSTRAINT CODCOMFKSCDETESTADOORDENPKCOMPANIA FOREIGN KEY(CODIGOSUCURSAL) REFERENCES SCDETSUCURSAL;
ALTER TABLE SCDETESTADOORDEN ADD CONSTRAINT CODUSRFKSCDETESTADOORDENPKUSUARIOREG FOREIGN KEY(USUARIOREGISTRO) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETESTADOORDEN ADD CONSTRAINT CODUSRFKSCDETESTADOORDENPKUSUARIOMOD FOREIGN KEY(USUARIOMODIFICACION) REFERENCES SCDETUSUARIO(USERID);
ALTER TABLE SCDETESTADOORDEN ADD CONSTRAINT CODPEDFKSCDETESTADOORDENPKORDEN FOREIGN KEY(CODIGOSUCURSAL, CODIGOORDEN) REFERENCES SCDETORDEN;